# Generated by Django 4.0.2 on 2022-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnh',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
