# Generated by Django 4.0.2 on 2022-03-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_cnh_user_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnh',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
