# Generated by Django 4.0.2 on 2022-04-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_cnh_alter_user_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('cpf', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountprofilemodel_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountprofilemodel_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountprofilemodel_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
