# Generated by Django 4.0.3 on 2022-04-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accountprofilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefone',
        ),
    ]
