# Generated by Django 4.0.3 on 2022-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_cnh_remove_user_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto do usuario'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_appuser',
            field=models.BooleanField(default=False, verbose_name='Pode acessar o app'),
        ),
    ]
