version: "3.3"

services:
  backend_redis:
    restart: always
    image: redis:alpine
    env_file:
      - .env-redis.yaml
      - .env-common.yaml
    expose:
      - 6379    

  django_db:
    restart: always
    image: postgis/postgis:14-master
    env_file:
      - .env-db.yaml  
      - .env-common.yaml
    expose:
      - 5432

  django_project:
    restart: always
    volumes:
      - "./django_project/:/home/django_project/"

    build:
      context: ./django_docker
      dockerfile: Dockerfile
    command: bash -c /home/django_project/entrypoint.sh
    expose:
      - 8001
      - 8002

    env_file:
      - .env-db.yaml
      - .env-api.yaml
      - .env-redis.yaml
      - .env-memcache.yaml
      - .env-common.yaml

    depends_on:
      - backend_redis
      - django_db


  nginx_static_server:
    restart: always
    build:
      context: ./nginx_server
      dockerfile: Dockerfile

    env_file:
      - .env-nginx.yaml
      - .env-common.yaml
      - .env-api.yaml

    volumes:
      - "./django_project/:/home/django_project/"
    ports:
      - 9055:80

    depends_on:
      - django_project
      - backend_redis

volumes:
  static_volume:
  media_volume:
  datastore_volume:
  
