# Generated by Django 3.2.8 on 2021-12-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('imagem_raw_data', models.TextField(blank=True)),
                ('raw_data_ready', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rest image',
                'verbose_name_plural': 'Rest image',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
