# Generated by Django 3.2.8 on 2021-12-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfiles', '0003_restimagemodel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='restimagemodel',
            name='altura',
            field=models.PositiveSmallIntegerField(default=128),
        ),
        migrations.AddField(
            model_name='restimagemodel',
            name='largura',
            field=models.PositiveSmallIntegerField(default=128),
        ),
    ]
