# Generated by Django 3.2.8 on 2021-12-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfiles', '0005_restimagemodel_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restimagemodel',
            name='criado_por',
        ),
        migrations.AddField(
            model_name='restimagemodel',
            name='isRemoved',
            field=models.BooleanField(default=False),
        ),
    ]
