# Generated by Django 3.2.10 on 2021-12-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfiles', '0007_restimagemodel_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restimagemodel',
            name='isActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='restimagemodel',
            name='isPublic',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='restimagemodel',
            name='isRemoved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
